import { Flex, VStack } from "@chakra-ui/react";
import { User, Video, VideoLikes } from "@prisma/client";
import Head from "next/head";
import { useEffect, useState } from "react";
import Profile from "../components/Profile";
import Videos from "../components/Videos";
import { prisma } from "../lib/prisma";

export async function getServerSideProps() {
  try {
    const data = await prisma.user.findUnique({
      where: {
        id: 1,
      },
      include: {
        videos: { include: { author: true, VideoLikes: true } },
        followedBy: true,
      },
    });
    return { props: { profile: JSON.parse(JSON.stringify(data)) } };
  } catch (error) {
    console.log(error);
    return;
  }
}

const Home = ({
  profile,
}: {
  profile: User & { videos: Video[]; followedBy: User[] };
}) => {
  const [user, setUser] = useState<User>(profile);

  useEffect(() => {
    const createUser = async () => {
      const data = await fetch(`/api/create`);
      const res = await data.json();
      setUser(res);
    };
    createUser();
  }, []);

  return (
    <VStack h={"2361px"} maxW={"1920px"} bgColor={"#000000"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        flexDirection={"column"}
        w={"1336px"}
        h={"2103px"}
        gap="24px"
        mt={"129px"}
      >
        <Profile profile={profile} user={user} />
        {profile.videos.map((video: any) => (
          <Videos key={video.id} video={video} user={user} />
        ))}
      </Flex>
    </VStack>
  );
};

export default Home;
